### ISSUE TITLE
Autobahn Failure: Inconsistent handling of ping/pong when behind IIS and AspNetCoreModule

### ISSUE THREAD

**Issue by anurse** [aspnet/WebSockets#100]
When our managed web socket implementation is running behind ANCM, we see inconsistent failures in the Autobahn test suite, particularly in the cases that relate to ping/pong handling in the midst of a fragmented message.

The general pattern that appears is that when the following sequence is sent:

1. First fragment of a message
2. Ping
3. Second and final fragment of a message

The result is that a Pong is returned by the server but the connection is terminated. I'm working on a repro using a C# client for this specific scenario, however it would be no different from the Autobahn test client. The failure is transient and does not always occur.

It can be reproduced locally by running the `AutobahnTestApp` in this repo using the instructions in the `test\AutobahnTestApp\README.md` file in this repo (once my branch is merged ;))

/cc @pan-wang - This is the issue I've referred to in email. It should be reproducible with the test app referenced.

**Comment by anurse** [comment]
I tried to set up a standalone C# repro but the C# WebSocket libraries do not give access to sending ping frames, which is required to reproduce this issue, so I've done what I can to make the Autobahn Test Suite case easy to reproduce.

**Setup:**
1. Install CPython 2.7 - https://www.python.org/downloads/release/python-2712/
2. Run `python -m ensurepip`
3. Run `pip install autobahntestsuite`
4. Run `wstest --help` to verify the test suite is installed

**Repro:**
1. Clone this repo, check out `anurse/100-repro`
2. Open WebSockets.sln in VS, and launch AutobahnTestApp in the IIS Express launch profile
3. Upon launching, the browser should pop and display the WebSocket URL for the server
4. Open PowerShell, cd to the `test\AutobahnTestApp` directory in this repo
5. Run `.\scripts\RunAutobahnTests.ps1 -ServerUrl [WEB SOCKET URL HERE] -Cases "5.7" -Iterations 20`

**Expected Behavior:** All iterations pass.

**Actual Behavior:** Some iterations will fail.

The test case is simply sending three frames:
* Opcode 1 (Text Frame) EndOfMessage=false "fragment1"
* Opcode 9 (Ping Frame) EndOfMessage=true "ping payload"
* Opcode 0 (Continuation Frame) EndOfMessage=true "fragment2"

The tests fail intermittently and without pattern. However, they do reliably fail within about 5-10 iterations. Something on the IIS end is dropping the connection because if you repeat the same tests directly against Kestrel it passes reliably (so far I've tried 20 iterations in sequence, now trying a 100 iteration pass).

**Comment by muratg** [comment]
Putting in 1.1 for now for further investigation to see if there are possible product bugs in the stack

**Comment by anurse** [comment]
Verified that this is an IIS issue. Created bug #8376897 in the WSSC TFS database and assigned to @pan-wang
