### ISSUE TITLE
Autobahn Failure: Many failures when in non-Windows over SSL

### ISSUE THREAD

**Issue by anurse** [aspnet/WebSockets#102]
Most of the test cases fail when running on a non-Windows platform using Kestrel's built-in SSL implementation.

**Comment by Tratcher** [comment]
'Most'? Does the client just not like the self-signed cert?

**Comment by anurse** [comment]
No, the handshake completes and then the connection terminates abruptly at some point.

**Comment by muratg** [comment]
Putting in 1.1 for now for further investigation to see if there are possible product bugs in the stack

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2477
