### ISSUE TITLE
Remove WebSocketOptions.ReplaceFeature

### ISSUE THREAD

**Issue by Tratcher** [aspnet/WebSockets#106]
This is a weird edge case for servers like WebListener that expose both opaque upgrades and WebSockets.

Always use the ReplaceFeature = false behavior. If someone wants to suppress the server implementation they can do so in a separate middleware:

```
app.Use((context, next) =>
{
  context.Features.Set<IHttpWebSocketFeature>(null);
  return next();
});
app.UseWebSockets();
```

**Comment by davidfowl** [comment]
:shipit:
