### ISSUE TITLE
When corefx code is removed, revisit warning suppressions

### ISSUE THREAD

**Issue by anurse** [aspnet/WebSockets#107]
When we remove the corefx internal code (before RTM), we need to revisit warning suppressions since most of them were added to suppress warnings in that code.

**Comment by stephentoub** [comment]
What warnings for what code? corefx code should be building warning-free.

**Comment by Tratcher** [comment]
https://github.com/aspnet/WebSockets/pull/105/files#r73249470

**Comment by Tratcher** [comment]
I hit the same errors in WebListener

**Comment by anurse** [comment]
I'd rather not mess with the corefx code in this case since if these warnings aren't occurring there, we'll keep having them pop up when we pull in new code. For now, since this code is temporary, suppressing these warnings is pretty benign.

I'm going to move the suppressions to the files themselves though (via our copy script)

**Comment by stephentoub** [comment]
https://github.com/dotnet/corefx/pull/10792

**Comment by anurse** [comment]
No changes are needed here. Our warning suppressions are now in line with other ASP.NET repos.
