### ISSUE TITLE
Websockets failed to open connection using iis 7.5, but working as console app

### ISSUE THREAD

**Issue by Flappiez** [aspnet/WebSockets#113]
My web app works fine as a console app on win 2008 R2 including the websockets, but from the minute I host it under IIS 7.5 it fails to create websockets.

Is there a way to get a working websocket while hosted on IIS 7.5 on Win2008R2? Every documentation I have found until now stated that websockets only work on IIS8, but the asp.net core requirements are win2008R2...

Please tell me that IIS7.5 and asp.net core have working websockets.

**Comment by davidfowl** [comment]
WebSockets on IIS requires Windows 8/Windows Server 2012.

**Comment by Flappiez** [comment]
Thank you for the answer. May I suggest that you change the documentation of "Supported operating systems" (link below) or at least append an extra asteriks :-)

> Supported operating systems
> 
> The following operating systems are supported:
> 
>     Windows 7 and newer
>     Windows Server 2008 R2 and newer*
> 
> *Conceptually, the IIS configuration described in this document also applies to hosting ASP.NET Core applications on Nano Server IIS, but refer to ASP.NET Core on Nano Server for specific instructions.
> 

https://docs.asp.net/en/latest/publishing/iis.html

**Comment by Flappiez** [comment]
For others looking at this "problem":

Instead of using IIS7.5 directly i setup a service using the other post of david "Running as Windows service #1386". And forward all calls to that service from iis.
