### ISSUE TITLE
Investigate a "copyless" API

### ISSUE THREAD

**Issue by anurse** [aspnet/WebSockets#116]
When https://github.com/aspnet/KestrelHttpServer/pull/1105 lands in Kestrel, it will be possible to provide a "copyless" (or very low copy) WebSockets API, where we return the buffers provided by Kestrel directly. This will allow for a pull API for websockets (something like `var msg = await socket.ReceiveAsync(...)`) where we don't have to do any copying into user buffers.

This issue tracks the investigations and work to explore that model.

Things to do:
- [ ] Performance measurement tool. We need a way to capture benchmarks and see what (if anything) improves.
- [ ] Build the new API and check performance
- [ ] ???
- [ ] Profit!

**Comment by muratg** [comment]
Sockets work will subsume this.
