### ISSUE TITLE
What's the current state of this project?

### ISSUE THREAD

**Issue by TAGC** [aspnet/WebSockets#121]
I'm trying to use migrate a .NET Framework-based web application to .NET Core, and I need it to be able to communicate with clients over websockets. I'm having issues sending data from the server back to clients ([further details here](http://stackoverflow.com/questions/39894258/asp-net-core-websocket-server-connection-killed-when-trying-to-send-data-to-cl)).

I've tried cloning this repo and trying out the samples. One issue is that the `project.json` for `EchoApp` references `Microsoft.NETCore.App 1.1.0-preview1-001090-00`, which I don't have installed and can't seem to find. I can see that this is an issue in your failing Travis builds too:

```
fail: The specified framework 'Microsoft.NETCore.App', version '1.1.0-preview1-001090-00' was not found.
fail:   - Check application dependencies and target a framework version installed at:
fail:       /home/travis/.dotnet/shared/Microsoft.NETCore.App
fail:   - The following versions are installed:
fail:       1.0.0
fail:   - Alternatively, install the framework version '1.1.0-preview1-001090-00'.
```

If I try to target v1.0.1 of `Microsoft.NETCore.App` (the latest released version as far as I'm aware), the server launches but fails to communicate similarly to with my own web application.

Is websocket support for ASP.NET Core essentially broken right now or is there a way to resolve these issues?

**Comment by Tratcher** [comment]
The devs branch may be more difficult to consume right now as we update our dependencies. Try the master branch instead.

**Comment by muratg** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.
