### ISSUE TITLE
WebSocket Middleware considers `Connection: keep-alive, upgrade` as non-WebSocket request

### ISSUE THREAD

**Issue by anurse** [aspnet/WebSockets#123]
Firefox sends it's WebSocket upgrade request with a Connection header value of `keep-alive, Upgrade`.  But we check for the header to exactly equal `Upgrade`. https://github.com/aspnet/WebSockets/blob/4e2ecf8a63b9fc78175d1ef62bf2b1918b8b3986/src/Microsoft.AspNetCore.WebSockets/Internal/HandshakeHelpers.cs#L38

Similar to https://github.com/aspnet/KestrelHttpServer/issues/1170

**Comment by anurse** [comment]
Ping @muratg for Triage. I assume 1.1.0 RTM for now.

**Comment by Tratcher** [comment]
This implementation is actually OK. See https://github.com/aspnet/WebSockets/blob/4e2ecf8a63b9fc78175d1ef62bf2b1918b8b3986/src/Microsoft.AspNetCore.WebSockets/WebSocketMiddleware.cs#L78 where it splits the header values.

This is only blocked by the kestrel issue. It works with WebListener.

**Comment by muratg** [comment]
Closing based on @Tratcher's input.
