### ISSUE TITLE
Optional keep-alive ping-pongs

### ISSUE THREAD

**Issue by shravan2x** [aspnet/WebSockets#134]
I have a server that receives less traffic. This means long-running websockets that are idle for many minutes. On its own, this is alright. But CloudFlare cuts idle sockets after exactly 100s of inactivity. [This](https://stackoverflow.com/questions/39668410/whats-disconnecting-my-websocket-connection-cloudflare-apaches-mod-proxy) post is not mine, but it captures the essence of the problem.

@Tratcher says in #90 that the current implementation processes these pings anyway. From what I understand, the problem is that both the browser and the server are built to process pings but neither of them actually initiates one. Could we have a way to do this (Maybe a setting while creating the sockets)?

**Comment by Tratcher** [comment]
This option is already available, see WebSocketOptions.KeepAliveInterval. The default is 2 minutes.

**Comment by shravan2x** [comment]
That solved the issue. For anyone else who passes by here, this is the code you need:

```
app.UseWebSockets(new WebSocketOptions { KeepAliveInterval = TimeSpan.FromSeconds(60) });
```
