### ISSUE TITLE
Long running websockets using IIS

### ISSUE THREAD

**Issue by garcus** [aspnet/WebSockets#169]
I have a problem when I have long running websocket connections open and the server is recycled from IIS (or website stopped). I thought I'd handle closing open websockets in a registered ApplicationStopping handler in ApplicationLifetime but it is never called. As long as I have open websockets I have no way of controlling the recycle-process.

Is this right, or am I missing something? Shouldn't it be possible to either force open websockets to be closed on recycle (as an option) or even better, be able to register a handler with appropriate actions to prevent process from hanging around until all websockets are closed from client side ?

**Comment by Tratcher** [comment]
@pan-wang @shirhatti

**Comment by garcus** [comment]
Any chance of finding a solution to this issue ? A workaround perhaps ? 
At this moment I'm forced to script process kill to be able to deploy new websites as the IIS-stopped websites are kept open by long running websocket connections to the kestrel-process.

**Comment by pan-wang** [comment]
As websocket connection holds an IIS pipeline, apppool recycling will have to wait for the close of the websocket connection till the apppool shutdown timeout is hit (default 90 seconds). One workaround is to set the timeout value to a smaller value if you have the permission to update IIS apppool settings.

ANCM itself does not listen to IIS AppPool shutdown notification yet and thus will not be able to notify the backend about shutting down.  Will change the design to address this scenario in the future if possible.

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2470
