### ISSUE TITLE
[question] Is there a way to handle unsafe close ?

### ISSUE THREAD

**Issue by John0King** [aspnet/WebSockets#182]
How to handle unsafe close?  and why the websocket is not event based ( `OnClose() `  ) ?

**Comment by Tratcher** [comment]
An unsafe close (e.g. closing the socket without a close message) by the remote party is represented as an exception (WebSocketException?) thrown from ReceiveAsync. You can catch this and deal with it as you see fit.

**Comment by davidfowl** [comment]
There's a specific error code for this (it's a connection reset).

**Comment by davidfowl** [comment]
> and why the websocket is not event based ( OnClose() ) ?

That's a good question. My guess is that it was made to match our existing Socket APIs rather than the browser API. See this API suggestion https://github.com/dotnet/corefx/issues/20583.

**Comment by John0King** [comment]
> You can catch this and deal with it as you see fit.

@Tratcher  @davidfowl  do I need call `Close()` or `Dispose()` on WebSocket Object  after I catch the WebSocketException ?  or use a `using(websocket) {  .... }`

Could you update  a  full example code  in samples folder , it will be very helpful !

**Comment by davidfowl** [comment]
@Tratcher we should really be doing that at the end of a web socket request.

**Comment by Tratcher** [comment]
Fair. That'd be a finally block here:
https://github.com/aspnet/WebSockets/blob/de8b7e7d3c06272a840859b365c37618c39ed78a/src/Microsoft.AspNetCore.WebSockets/WebSocketMiddleware.cs#L48

that removed and disposed the feature and it's associated WebSocket (if any).

**Comment by muratg** [comment]
@Tratcher good to close?

**Comment by Tratcher** [comment]
@muratg no, @davidfowl asked for a code change.

**Comment by davidfowl** [comment]
Closing this and opening a new bug.
