### ISSUE TITLE
Upgrade TargetFramework in TestServer from 4.5 to 4.6.1

### ISSUE THREAD

**Issue by mikeharder** [aspnet/WebSockets#185]
The target framework for samples\TestServer is currently 4.5.  It should be upgraded to 4.6.1 to align with the rest of ASP.NET Core and to require one less dependency to build the WebSockets repo.

**Comment by muratg** [comment]
@mikeharder Moving this to 2.1.0.  But if you'd like to get it in before, please bring it back.
