### ISSUE TITLE
Error on successful http call while websockets connection is open

### ISSUE THREAD

**Issue by risogolo** [aspnet/WebSockets#187]
I'm getting an exception and my websockets connection is terminated when I call http call to any endpoint inside socket.ReceiveAsync method

`System.Net.WebSockets.WebSocketException: The remote party closed the WebSocket connection without completing the close handshake. ---> System.IO.IOException: Error -4077 ECONNRESET connection reset by peer ---> Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvException: Error -4077 ECONNRESET connection reset by peer --- End of inner exception stack trace --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Net.WebSockets.ManagedWebSocket.<EnsureBufferContainsAsync>d__69.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Net.WebSockets.ManagedWebSocket.<ReceiveAsyncPrivate>d__60.MoveNext() --- End of inner exception stack trace --- at System.Net.WebSockets.ManagedWebSocket.<ReceiveAsyncPrivate>d__60.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter1.GetResult()`

**Comment by davidfowl** [comment]
Can you provide a sample?

**Comment by risogolo** [comment]
public async Task Invoke(HttpContext context)
        {
                if (!context.WebSockets.IsWebSocketRequest) 
                {
                   await _next.Invoke(context);
                    return;
                }

                var socket = await context.WebSockets.AcceptWebSocketAsync("json-rpc");

            var id = _socketManager.AddSocket(socket);

                await Receive(socket, async (result, buffer) =>
                {
                    using (HttpClient client = new HttpClient())
                    {
                        client.BaseAddress = new Uri("http://www.pc.sk");
                        var x = await client.GetAsync(new Uri("http://www.pc.sk")); //exception thrown
                    }
                   

                    if (result.MessageType == WebSocketMessageType.Close)
                    {
                        await _socketManager.RemoveSocket(id);
                    }
                });
        }

        private async Task Receive(WebSocket socket, Action<WebSocketReceiveResult, byte[]> handleMessage) //presunut do managera
        {
            var buffer = new byte[1024 * 4];

            while (socket.State == WebSocketState.Open)
            {
                try
                {
                    var result = await socket.ReceiveAsync(buffer: new ArraySegment<byte>(buffer), cancellationToken: CancellationToken.None);

                    handleMessage(result, buffer);
                }
                catch (Exception e)
                {
                    Console.WriteLine(e);
                    throw;
                }
            }
        }`

**Comment by davidfowl** [comment]
That's because you  end the receive loop if there's an exception. Just catch the exception and it won't terminate the websocket. If the task ends, the websocket will die.

**Comment by risogolo** [comment]
No, it's terminated anyway even if I don't rethrow the exception, but the question is why even exception is thrown on successful http call?

**Comment by davidfowl** [comment]
Get rid of the http client call and just throw an exception. Does it still end? I don't think there's anything special about http client throwing that would cause it to fail. Are you sure it's not failing somewhere else?

**Comment by risogolo** [comment]
```
private async Task Receive(WebSocket socket, Action<WebSocketReceiveResult, byte[]> handleMessage) 
    {
        var buffer = new byte[1024 * 4];

        while (socket.State == WebSocketState.Open)
        {
var result = await socket.ReceiveAsync(buffer: new ArraySegment<byte>(buffer), cancellationToken: CancellationToken.None);

            try
            {
                handleMessage(result, buffer);
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                throw;
            }
        }
    }
```

**Comment by davidfowl** [comment]
@risogolo So one thing you're doing that isn't great. The callback should be `Func<WebSocketReceiveResult, byte[], Task>` not Action. The Receive loop should be awaiting the handleMessage call. That might be the problem.

**Comment by risogolo** [comment]
Thank you David, one more thing which does not belong here, but I cannot find any related information, what is different between 
https://www.nuget.org/packages/Microsoft.AspNetCore.WebSockets.Server/ 
and
https://www.nuget.org/packages/Microsoft.AspNetCore.WebSockets/

also if you think the previous "issue" is not actually an issue you can close it

**Comment by davidfowl** [comment]
> also if you think the previous "issue" is not actually an issue you can close it

It's a bug in the code.

> Microsoft.AspNetCore.WebSockets.Server

This is deprecated.

**Comment by risogolo** [comment]
@davidfowl: do you mean in my code or? in websockets library code itself

**Comment by davidfowl** [comment]
In your code, what I called out is likely the issue. The websocket shouldn't just close for arbitrary exceptions happening.
