### ISSUE TITLE
No ability to set TcpClient.NoDelay to true

### ISSUE THREAD

**Issue by ninjasource** [aspnet/WebSockets#196]
Hi,

There does not seem to be a way to configure the underlying socket connection to send small messages immediately. You would typically do this on a simple TcpClient by setting the NoDelay property to true. As it now stands the application will wait a few milliseconds for more potential data before it completes a TCP segment and puts it on the wire. Would it be possible to enable this behaviour somehow? This would be very beneficial for low latency applications.

Thanks

**Comment by Tratcher** [comment]
You're looking at the wrong layer. WebSockets don't own the underlying socket, the server does. I suggest asking this question in https://github.com/aspnet/KestrelHttpServer.

**Comment by davidfowl** [comment]
> There does not seem to be a way to configure the underlying socket connection to send small messages immediately. You would typically do this on a simple TcpClient by setting the NoDelay property to true. As it now stands the application will wait a few milliseconds for more potential data before it completes a TCP segment and puts it on the wire. Would it be possible to enable this behaviour somehow? This would be very beneficial for low latency applications.

Also NoDelay is true by default.
