### ISSUE TITLE
KeepAliveInterval doesn't seem to work

### ISSUE THREAD

**Issue by nehmebilal** [aspnet/WebSockets#204]
In my StartUp class of ASP.Net app hosted using WebListener, I am adding the WebSocketMiddleware as follows:

```csharp
            var webSocketOptions = new WebSocketOptions
            {
                KeepAliveInterval = TimeSpan.FromSeconds(30),
            };
            app.UseWebSockets(webSocketOptions);
```

Then I am creating WebSockets as follows:

```csharp
        public async Task Configure(HttpContext hc, Func<Task> next)
        {
           var webSocket = hc.WebSockets.AcceptWebSocketAsync();
           /// ...
        }
```

The value I use for KeepAliveInterval doesn't seem to have any effect and it still seems to take up to 2 minutes to send a ping.

I am currently using Microsoft.AspNetCore.WebSockets 1.0.2.

Am I doing anything wrong?

**Comment by Tratcher** [comment]
Takes up to 2 minutes for what? To send a Ping?

**Comment by nehmebilal** [comment]
Yes.

**Comment by nehmebilal** [comment]
Any thoughts?

**Comment by Tratcher** [comment]
The relevant code:
https://github.com/aspnet/WebSockets/blob/c65e8681c4a50fc33c263d1f42dfcf007cb5c035/src/Microsoft.AspNetCore.WebSockets/Internal/fx/src/System.Net.WebSockets.Client/src/System/Net/WebSockets/ManagedWebSocket.cs#L487-L501
It does have that else clause that says it will skip sending a Ping if any other send is already in progress.

**Comment by nehmebilal** [comment]
Ok. In my experiments, there was pretty much no traffic other than the pings so there shouldn't be any contention on the lock.

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2464
