### ISSUE TITLE
Provide some guidance for managing WebSocket lifetime

### ISSUE THREAD

**Issue by anurse** [aspnet/WebSockets#208]
We've had a few reports from customers who are taking the `WebSocket` object, handing it off to a background thread and then allowing the request thread to complete. This causes the underlying connection to be closed and breaks the WebSocket. We should consider providing some guidance (a sample, blog post, docs, even changes to behavior if we feel that's valid) to help customers understand how the lifetime of the WebSocket needs to be managed.

**Comment by Tratcher** [comment]
@BrennanConroy does SignalR do this too? What's the pattern used there?

**Comment by anurse** [comment]
I think the right pattern to document for today is something like this:

```csharp
app.Use(async (context, next) => {
    var socket = await context.WebSockets.AcceptWebSocketAsync();
    var tcs = new TaskCompletionSource<object>();
    BackgroundProcessor.Enqueue(socket, tcs);
    await tcs.Task;
});
```

**Comment by anurse** [comment]
There's also something to be said asking if there's any value in moving the socket to a background processor in this model. You have to block the request thread anyway. Maybe people are coming from an ASP.NET 4.x model where Request Threads are somehow "special", whereas IIRC ours are just ThreadPool threads.

**Comment by Tratcher** [comment]
My understanding is that they are usually handing the socket off to a central management system. E.g. Something that wants to broadcast to all connected sockets.

Does a wrapper help any? It's one less object to track.
```
app.Use(async (context, next) => {
    var socket = await context.WebSockets.AcceptWebSocketAsync();
    var lifetime = new WebSocketLifetime(socket);
    BackgroundProcessor.Enqueue(lifetime);
    await lifetime.Task;
});
```

**Comment by anurse** [comment]
I don't know if I would want us to create such a thing. I'd imagine there may be other context data a user would want to capture (HttpContext, etc.).

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2462
