### ISSUE TITLE
Add EventSource/EventCounter tracing and metrics for WebSockets

### ISSUE THREAD

**Issue by anurse** [aspnet/WebSockets#209]
Some events listed below. The goal is to add events that will help users solve problems so if these aren't going to do that job, feel free to suggest/discuss others!

* `Microsoft-AspNetCore-WebSockets` EventSource
    * `ConnectionStarted` event - Triggered when a connection is established.
    * `ConnectionEnded` event - Triggered when a connection is terminated gracefully.
    * `ConnectionAborted` event - Triggered when a connection is terminated abnormally.
    * `FrameSent` event - Triggered when an frame is sent from the server.
    * `FrameReceived` event - Triggered when an frame is received by the server.
    * `PayloadBytesWritten` counter - Counts the number of payload bytes written.
    * `PayloadBytesRead` counter - Counts the number of payload bytes read.
    * `ConnectionDuration` counter - Measure the duration of each connection.
    * We could include some counters by frame type (Close, Ping, Pong, Text, Binary, Continuation, etc.) but many are hidden behind CoreFx.

Some of these may not be feasible given the WebSocket APIs, so we may need to adjust or cut some events. Or perhaps just not do any of them if it's not possible :).

See https://gist.github.com/anurse/af1859663ac91c6cf69c820cebe92303 for some guidance on adding EventSources and EventCounters to ASP.NET projects.

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2461
