### ISSUE TITLE
Update CoreFx Code

### ISSUE THREAD

**Issue by anurse** [aspnet/WebSockets#214]
We need to either update our CoreFx code in 2.1 **or** get the `CreateFromStream` API OOBed (https://github.com/dotnet/corefx/issues/21537) so we can use it.

Ping @muratg @Eilon : This should go in 2.1. Probably in preview1 if we can squeeze it in (at least updating the code from CoreFx, it's mostly automated via a script)

**Comment by kasper3** [comment]
Thank you!

If it's just a matter of running the powershell script and making sure CI passes all the tests, I can give it a quick try! Just hoping to get it in this year 💙

**Comment by anurse** [comment]
It **may** be that simple ;). Feel free to give it a shot. There may have been some new code added to corefx, and the files may have been moved around since we did it last time.

**Comment by kasper3** [comment]
Apparently it needs some more digging. The netstandard System.Net.WebSockets package doesn't have methods in WebSocket class that ManagedWebSocket is overriding.

I got to the point, where compiler (with latest KoreBuild) is complaining about `public override ValueTask<ValueWebSocketReceiveResult> ReceiveAsync(Memory<byte> buffer, CancellationToken cancellationToken)`, no method to override..

**Comment by anurse** [comment]
Ah yeah, they changed some APIs recently. I'll take a look at it and we'll try to get it up to date for preview 1.

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2459
