### ISSUE TITLE
Switch from System.Random to a crypto RNG provider

### ISSUE THREAD

**Issue by Eilon** [aspnet/WebSockets#26]
Talk to @GrabYourPitchforks about this and this is a must-fix.

In this code:
https://github.com/aspnet/WebSockets/blob/dev/src/Microsoft.AspNet.WebSockets.Protocol/CommonWebSocket.cs#L92-L112

We need to stop using System.Random and switch to using a proper crypto RNG provider.

**Comment by Eilon** [comment]
@muratg can you find someone to work on this?

**Comment by Tratcher** [comment]
ZeroMask is a debug setting so that you can read the data in Netmon. It just makes the masking step a no-op so it should work with any server.

**Comment by Eilon** [comment]
@Tratcher I moved the ZeroMask discussion to https://github.com/aspnet/WebSockets/issues/27 so we could treat it separately.

**Comment by anurse** [comment]
Is this still relevant @Tratcher @muratg @Eilon ? If so, we should move it to beta6

**Comment by Tratcher** [comment]
Yes, moved to beta6.

**Comment by anurse** [comment]
:+1:

**Comment by anurse** [comment]
FYI, `RNGCryptoServiceProvider` is not yet available on CoreCLR, so we'll have to continue using `System.Random` there. Mono does have a `RNGCryptoServiceProvider` implementation that uses `/dev/random` or `/dev/urandom` on *nix. We'd need to sync up with CoreCLR on the plan for implementing this there.

Is this OK @Eilon @Tratcher @muratg @blowdart ?

**Comment by Eilon** [comment]
I'm fine waiting.

**Comment by blowdart** [comment]
If you're already branching based on OS to use the Mono one, then why not pinvoke if you're on Windows whilst we wait.

**Comment by Eilon** [comment]
Gross :frowning:

**Comment by anurse** [comment]
Because I will likely introduce more bugginess and spend valuable time?

**Comment by Eilon** [comment]
Per what @anurse said, this would ironically make the behavior of the code even more random :trollface:

**Comment by blowdart** [comment]
A single if statement is more bugginess? I have way more faith in you than that Andrew :D

As gross as it is the RFC specifies PRNGs for a reason and we should make an effort here until CoreCLR catches up.

CryptGenRandom is what you want - https://msdn.microsoft.com/en-us/library/windows/desktop/aa379942%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396

**Comment by anurse** [comment]
Don't forget CryptAcquireContext and figuring out which container/provider I'm supposed to use :)

**Comment by blowdart** [comment]
Well yes, but just lift it from 4.6 framework code :p

**Comment by anurse** [comment]
@Eilon I think I'm going to need to get you to sign-off on doing that :)

**Comment by anurse** [comment]
I can do it though, it'll just take a bit for me to work out what to pull where and when. What are we going to do on CoreCLR Linux/Mac? Read from /dev/random ourselves?

**Comment by blowdart** [comment]
In Mono use their class, in Linux/Mac ... ummm, abort with notSupported? :D

**Comment by anurse** [comment]
WebSockets are not supported on CoreCLR Linux/Mac?

**Comment by blowdart** [comment]
If you can't support the RFC's intent should you support it at all?

**Comment by anurse** [comment]
The framework RNG has a bunch of tendrils through the rest of System.Security.Crypto to support custom CSP Parameters and such. Would it be safe to assume we don't need to support that and can just use the default CSP (i.e. parameterless ctor for RNGCryptoServiceProvider)?

**Comment by blowdart** [comment]
I think it'd do for now, until we can switch to their version.

**Comment by anurse** [comment]
At the moment it's very difficult for the WebSockets code to detect what kind of CoreCLR it is running on. @davidfowl and I talked and we think the most achievable result for beta6 is to #ifdef and use System.Random on CoreCLR. If that's not acceptable for now, we need to punt this bug to beta7 and work with the CoreCLR team to get either RNGCryptoServiceProvider or Platform-detection logic in ASAP.

**Comment by blowdart** [comment]
Or not support on core? Has anyone talked to coreclr about their timescales?

**Comment by PinpointTownes** [comment]
Heh, I thought that `RNGCryptoServiceProvider` support had been recently added to CoreCLR?
https://github.com/dotnet/corefx/commit/f394692c7de8cb9e3e9c1b6d3a72ba1196e0d28b
https://github.com/dotnet/corefx/pull/1944

**Comment by anurse** [comment]
Awesome, we just have to track down if we've got it in DNX now :)

**Comment by PinpointTownes** [comment]
I'm pretty sure there's a package for that: `System.Security.Cryptography.RandomNumberGenerator` :smile:

**Comment by anurse** [comment]
Indeed :)

**Comment by anurse** [comment]
If only our Package Search tool had been updated *cough* @glennc *cough* :P
