### ISSUE TITLE
Remove ZeroMask support

### ISSUE THREAD

**Issue by Eilon** [aspnet/WebSockets#27]
ZeroMask support is apparently only a dev-time optimization and isn't per-spec, and isn't really needed.

@Tratcher

**Comment by Tratcher** [comment]
ZeroMask is a debug setting so that you can read your data in Netmon. 0 is a legal mask per spec, just not recommended (see http://xkcd.com/221/). It makes the masking step a no-op, but servers shouldn't even notice.

**Comment by Eilon** [comment]
I think once you invoke an XKCD comic it becomes truth.

**Comment by Eilon** [comment]
@anurse mark as 3-Done and set milestone?
