### ISSUE TITLE
SendAsync, ReceiveAsync semantics inconsistency between different implementations

### ISSUE THREAD

**Issue by mkosieradzki** [aspnet/WebSockets#42]
There are some incosistencies in implementations of web sockets: (Helios, Reference:AspNetWebSocket, .NET Core:CommonWebSocket)

ReceiveAsync is not that bad:
1. HeliosWebSocket throws exceptions in case of two simultaneous ReceiveAsync are in place - this is consistent with reference documentation: http://referencesource.microsoft.com/#System.Web/WebSockets/AspNetWebSocket.cs ThrowIfReceiveUnavailable - checks for Busy state which is set during every ReceiveAsync
From my experiment HeliosWebSocket behaves the same
CommonWebSocket - does behave differently BUT! it has a proper code comment:             // TODO: InvalidOperationException if any receives are currently in progress.

So I can safely assume that reference semantics are the expected ones.
2. In case of SendAsync it's a bit worse:
It's well documented in reference implementation:
    // - We'll detect multiple calls to SendAsync (e.g. a second call takes place while the first
    //   call isn't yet complete) and throw an appropriate exception. CloseOutputAsync is
    //   an equivalent of SendAsync for this purpose.
HeliosWebSockets acts accordingly (from my experiments).
CommonWebSocket uses asynchronous _writeLock during entire operations - so it safely allows multiple subsequent SendAsync and there is not intention in comments to unify semantics.

What are the intended semantics for ASP.NET 5? Single SendAsync at a time and single ReceiveAsync at a time? And it is a bug? Or SingleReceiveAsync and multiple SendAsyncs at a time and HelliosWebSockets are going to be updated?

**Comment by Tratcher** [comment]
The synchronization you see in CommonWebSocket is used to prevent Ping/Pongs from colliding with user Sends. See:
https://github.com/aspnet/WebSockets/blob/dev/src/Microsoft.AspNet.WebSockets.Protocol/CommonWebSocket.cs#L377
https://github.com/aspnet/WebSockets/blob/dev/src/Microsoft.AspNet.WebSockets.Protocol/CommonWebSocket.cs#L164
https://github.com/aspnet/WebSockets/blob/dev/src/Microsoft.AspNet.WebSockets.Protocol/CommonWebSocket.cs#L124
https://github.com/aspnet/WebSockets/blob/dev/src/Microsoft.AspNet.WebSockets.Protocol/CommonWebSocket.cs#L489

This also happens to protect a user from calling Send multiple times by mistake, but that does not mean concurrent sends are actually supported.  You can see by the way the locks work that the user gets no benefit from calling Send multiple times at the moment. If it becomes a problem then we can add additional checks to notify users when they call send multiple times by mistake.

**Comment by davidfowl** [comment]
We can consider using a Task queue.

**Comment by Tratcher** [comment]
We already use SemaphoreSlim.WaitAsync, so it's async blocking.

**Comment by mkosieradzki** [comment]
IMO it's very important in xplat/pluggable libraries like WebSockets implementation to maintain exactly the same semantics (including error handling) among different implementations/platform. One could depend on implementation specifics for example task queuing on async semaphore instead of providing upper level buffering/queuing and for example application will work correctly when .NET Core self-hosted but will fail under Helios throwing InvalidOperationException.

**Comment by Tratcher** [comment]
Interestingly the MSDN docs do not specify a required semantic: https://msdn.microsoft.com/en-us/library/system.net.websockets.websocket.sendasync(v=vs.110).aspx

I understand the portability concern. Since the overlapped sends are not fully supported we should actively discourage developers at runtime from doing it (e.g. throw).

That said, if we decided to support overlapped sends in a specific implementation, we may do that even if other implementations didn't. Consistency is good, but sometimes we diverge on purpose to add value. Otherwise we'd never need more than one implementation.  We just need to be clear about the differences and why you'd use one over the other.

**Comment by mkosieradzki** [comment]
Yeah exactly. Unclear semantics on such core APIs are one of the root causes of inefficient networking implementations or portability issues. That's exactly why I started from browsing source code of different implementations due to lack of official documentation on this problem.

In case you decide to add support for Overlapped Sends/Receives please consider adding: `bool SupportsOverlapped { get; }` or something like that with clear semantics. In such situation libraries utilizing WebSocket can check for this flag and make use of optimization you are implementing ;).

For example I am implementing an xplat RPC library over web sockets and want it to be as efficient as possible (especially in terms of latency) but also interopable (working among different kinds of hosts).

**Comment by tmds** [comment]
Whether or not multiple sends are supported has an effect on the user-code, so the behavior should be specified in the documentation and should not vary across implementations.

In my opinion, every implementation should support multiple SendAsyncs.

**Comment by tmds** [comment]
Whether SendAsync and ReceiveAsync can be used simultaneously needs to be clarified as well.

Some 'typical' websocket use-cases which benefit from concurrent operation support:
- sending the same data to a number of client WebSockets (you don't want to await the Send for each client)
- sending event notifications from multiple independent sources to a client WebSocket
- accepting commands on a WebSocket and providing the reply after async execution (multiple replies can occur simultaneously)

**Comment by tmds** [comment]
With the adoption of the ManagedWebSocket semantics are the same accross implementations: "supports exactly one send and one receive on each WebSocket object in parallel".
This means we can close this issue.

**Comment by zygimantas** [comment]
I am not sure if this is a good place to ask, but this discussion is the closest thing I can find which related to the problem I am experiencing. Is it possible, that (await SendAsync(...)) returns  before the message is actually sent to the client? Is it by design, or it's a possible bug?

I noticed that by breaking the loop: 
    ```while(IsConnected()) { ... await SendAsync(...).ConfigureAwait(false); break; }```
It works fine on localhost (same machine as a client), but the message is never received if the service is published to Azure.

**Comment by Tratcher** [comment]
@zygimantas SendAsync completion only guarantees the WebSocket is done with the buffer you passed into it. It practice it means that it has formatted the WebSocket frame and written it to the next layer down (e.g. Sockets). It can't guarantee the message has been received by the client, or has even left the server. This is why WebSockets has a Close handshake, to make sure all data has been sent/received before you shut down the connection.
