### ISSUE TITLE
Fix exception parameter name in CommonWebSocket.ValidateSegment

### ISSUE THREAD

**Issue by Eilon** [aspnet/WebSockets#44]
See discussion here:
https://github.com/aspnet/WebSockets/commit/208fa4af366e23b51f2b943f709e00b6d48eec22#diff-2f20d3473af8bc60eee727dd88bbb804R595

The change to use `nameof()` makes the parameter name in the exception be incorrect.

**Comment by hishamco** [comment]
I will get a fix for this ASAP ..
FYI I need to look in almost the repos, because this may happen in another repo

**Comment by muratg** [comment]
I think the PR doesn't really fix it. IMO we'll just have to use magic strings in this case.

**Comment by muratg** [comment]
I put another suggestion in the PR.

**Comment by hishamco** [comment]
I already update the PR according your suggestion @muratg
