### ISSUE TITLE
IsWebSocketRequest is always false

### ISSUE THREAD

**Issue by tmds** [aspnet/WebSockets#46]
When I make a WebSocket connection the http pipeline is started but context.WebSockets.IsWebSocketRequest is false.

Stepping through the code shows me [upgradeFeature](https://github.com/aspnet/WebSockets/blob/c86b157ad3cd00e8848c4895fe29de2f9d81a0b4/src/Microsoft.AspNet.WebSockets.Server/WebSocketMiddleware.cs#L32) is null.

How can I get this to work?

**Comment by Tratcher** [comment]
Which server are you running on?

**Comment by tmds** [comment]
I tried running in IIS Express and using the 'web' command. They behave the same.
My iisexpress is v10, 32 bit.

**Comment by Tratcher** [comment]
What client are you using?  Maybe it's incompatible. Try this one for reference: https://github.com/aspnet/WebSockets/blob/dev/test/TestClient/Program.cs

**Comment by tmds** [comment]
I was using Chrome. The TestClient has the same behavior: upgradeFeature is null.

**Comment by davidfowl** [comment]
upgrade feature is supposed to be null but the websocket feature shouldn't be.

**Comment by tmds** [comment]
Should it be null at [this](https://github.com/aspnet/WebSockets/blob/c86b157ad3cd00e8848c4895fe29de2f9d81a0b4/src/Microsoft.AspNet.WebSockets.Server/WebSocketMiddleware.cs#L32) location?

Also IsWebSocketRequest remains false when using the TextClient.

**Comment by Tratcher** [comment]
IIS does not support the Upgrade feature, it supports WebSockets natively (e.g. you don't need to use the websocket middleware). WebListener supports both Upgrade and WebSockets natively, so using the middleware is optional.  Kestrel only supports Upgrade and requires the middleware for WebSockets.

**Comment by tmds** [comment]
So the upgrade feature isn't the root cause of the IsWebSocketRequest being false. What else could be causing it?

**Comment by tmds** [comment]
Which of the servers support WebSockets on Windows 7?

**Comment by muratg** [comment]
AFAIK you're out of luck with IIS or WebListener on Windows 7/Server 2008/R2. I believe WebSockets support to http.sys was only added in Windows 8 (and Server 2012+)   Kestrel could potentially work.

**Comment by tmds** [comment]
I tried Kestrel, but it isn't working even for non-websocket http. I can step through the Startup.Configure but my app.Run http pipeline isn't called. So another issue seems to occur there.

Is there an API I can use to query the server features so I can figure out whether the web server supports websockets natively, or if it will after using the WebSocket middleware or it if won't at all?

**Comment by davidfowl** [comment]
@tmds You should always use the websocket middleware it will light up websockets if the server doesn't support it and it already queries the server for the feature.

**Comment by tmds** [comment]
When you use the middleware, is there are a way to figure out the server still won't support websockets?

**Comment by davidfowl** [comment]
You can check for the feature yourself. `context.GetFeature<IHttpWebSocketFeature>()`

**Comment by tmds** [comment]
Is it possible without having a request, e.g. in the Startup class?
This would make it possible to inform the client websockets are not supported.
SockJS for example has a json info resource which returns whether the server supports websockets.

**Comment by Tratcher** [comment]
That's not available yet. We used to have this kind of startup detection in Katana, but haven't developed a replacement.

**Comment by tmds** [comment]
I'm closing this issue as the root cause is websockets are not supported on Windows 7 with IIS/WebListener.
There is no way to detect in the ASP.NET application whether the OS+webserver+WebSockets middleware will support websockets or not. It would be nice if there was.
