### ISSUE TITLE
Shouldn't this package also provide an implementation of IHttpUpgradeFeature?

### ISSUE THREAD

**Issue by Flavien** [aspnet/WebSockets#47]
It seems the UseWebSockets extension does nothing unless a IHttpUpgradeFeature is available.

Wouldn't it make sense to provide an implementation and an easy way to add the feature for hosts where it's not available?

**Comment by Tratcher** [comment]
Upgrade isn't a capability that can be added by middleware, it must be naivety supported by servers. Most servers do not give you the direct access to the underlying connection that you need for WebSockets.

**Comment by Flavien** [comment]
I see, that makes sense. On what platforms/hosts is that supported?

**Comment by Tratcher** [comment]
Upgrade is supported by WebListener on Win8+, or by Kestrel on any OS.

Note that IIS and WebListener have native WebSocket support, so the middleware won't do anything on those by default.
