### ISSUE TITLE
WebSocketHandler.SendAsync can throw

### ISSUE THREAD

**Issue by jods4** [aspnet/WebSockets#60]
I am unsure if you will consider that a bug (or design flaw) or not. 

Looking at the source, and given that using websockets is very async by nature (disconnection can happen any time), I assumed that calling `SendAsync` was safe and need not a `try..catch` around it.

But in fact, it's not. It checks `WebSocket.Status`, which throws when `WebSocket` was disposed (at least the `HeliosWebSocket` does -- I know you dropped Helios, I just haven't tested another implementation yet). So if the socket is closed (e.g. client disconnects) at the bad time `SendAsync` will throw.

Solutions:
- wrap all your calls to `SendAsync` in `try..catch` but that doesn't quite feel right.
- in your derived `SebSocketHandler` add some kind of synchronization between `OnClose` and `SendAsync` (and probably others) so that this could not happen. This is hard and looks like an easy pitfall to me.

I think the good solution is either:
- `WebSocketHandler` should fixed to not throw. E.g. not check `WebSocket.Status` in the main part (it does again in a task), or check it inside a `try..catch`.
- or `WebSocket.Status` should not throw even when disposed. It can return an appropriate status instead.

**Comment by Tratcher** [comment]
WebSockets are doing IO so every SendAsync and ReceiveAsync call needs to have exception management anyways.

**Comment by jods4** [comment]
@Tratcher Sorry I posted this in the wrong project. Should be under SignalR-Server.

I am talking about `WebSocketHandler.SendAsync`, which does already wrap `WebSocket.SendAsync` in a try/catch block. It seems clear from the code (because there's even misplaced logging code) that the intent is not to let an exception escape and log any failure.

**Comment by Tratcher** [comment]
This issue was moved to aspnet/SignalR-Server#134
