### ISSUE TITLE
The dependency Microsoft.AspNet.WebSockets.Client 1.0.0-rc1-final does not support framework DNXCore,Version=v5.0

### ISSUE THREAD

**Issue by Flavien** [aspnet/WebSockets#62]
There is an issue with Microsoft.AspNet.WebSockets.Client: when trying to add it to a .NET Core project, I receive the following error:

```
The dependency Microsoft.AspNet.WebSockets.Client 1.0.0-rc1-final in project XXX does not support framework DNXCore,Version=v5.0.
```

Shouldn't it target dnxcore50 as well?

**Comment by tmds** [comment]
See https://github.com/aspnet/WebSockets/issues/61

**Comment by muratg** [comment]
@Tratcher IIRC we talked about this at some point.  Were we waiting for CoreCLR support to make client work in .NET Core?

**Comment by Tratcher** [comment]
https://github.com/aspnet/WebSockets/issues/61#issuecomment-157876548
