### ISSUE TITLE
Native/Managed clarification

### ISSUE THREAD

**Issue by zygimantas** [aspnet/WebSockets#73]
Could you please add more information to readme file about what is the difference between native and managed implementations and in which cases the managed one should be preferable.

**Comment by muratg** [comment]
@zygimantas FYI, WebSockets will not RTM with the rest of the stack, instead will stay in Preview until we can properly finish the work.

This is a pure managed library, designed to work with ASP.NET Core stack. Once it's properly implemented, you should be using it with ASP.NET Core.

**Comment by zygimantas** [comment]
Thanks @muratg , I am aware that it is in preview. But I missed a little bit of the background on this project, and I found out that if you want to get WebSockets working while debugging in Visual Studio 2015 using IIS Express 10.0 on Windows 10, you still have to use this project and configure app.UseWebSockets() in your Startup.cs file. Otherwise, IsWebSocketRequest will be false. I could not find any information on this subject. So, I guess, you must use this managed implementation if you run ASP.NET Core project on IIS Express. I haven't tested that on IIS, and I believe the websockets should work natively without using a separate websockets nuget package?

**Comment by Tratcher** [comment]
You need this project regardless when working with Kestrel (with or without IIS/Express). WebListener has it's own native implementation, but can also work with this one.

Part of the reason we're not shipping WebSockets yet is that we haven't done a meaningful comparison to answer your question.

**Comment by muratg** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.
