### ISSUE TITLE
Support for Ping-pong with callback

### ISSUE THREAD

**Issue by gdoron** [aspnet/WebSockets#74]
Hi,

It would be nice if the package would support the server initiating a ping to the client to check if it's still connected or not.
Currently (and please correct me if I'm wrong) the only to make sure the server doesn't accumulates already dead web sockets is the do ping-pong with messages instead of ping-pong frames.

Thanks,
Doron

**Comment by Tratcher** [comment]
There is already a built in timer based ping-pong system.
https://github.com/aspnet/WebSockets/blob/dev/src/Microsoft.AspNetCore.WebSockets.Server/WebSocketOptions.cs#L24

**Comment by gdoron** [comment]
@Tratcher Unless I'm missing something obvious, the timer only sends pings which is quite useless unless we can plugin to the pipeline and take actions if no pong was received. 

https://github.com/aspnet/WebSockets/blob/9beb46dff111741cffd8eb64db255a3f0446c424/src/Microsoft.AspNetCore.WebSockets.Protocol/CommonWebSocket.cs#L165-L208.

Thanks again for the quick responses!

**Comment by Tratcher** [comment]
Ping and Pongs aren't uniquely paired in the protocol, they are just control messages used to keep the pipe alive and/or check for pipe failures. You don't need to verify a pong is received for every ping, the  ping alone should be enough to verify the pipe is active or trigger a send failure (e.g SocketException).

**Comment by gdoron** [comment]
@Tratcher I read the spec a bit. I understand it now (not why they decided to confusingly call it ping-pong...)
Thanks.
