### ISSUE TITLE
WebsocketHandler.Send is sometimes not working

### ISSUE THREAD

**Issue by NVentimiglia** [aspnet/WebSockets#75]
I am using the WebsocketHandler in an MVC application. On the client I am using WebsocketsSharp on the Unity3d platform. Everything works fine on the first / fresh launch. I boot up the server, I connect the client, and they communicate fine.

If I disconnect the client and reconnect it, things start breaking. Specifically calling the WebsocketHandler.Send method stops working. I can still send to the server from the client. I can still communicate with the client via using the WebsocketCollection.Broadcast() method.

I was wondering what I could do to debug this.

Did a little more debuging. Restarting the client does not help. In fact, sometimes restarting the server does not help. What does help is killing the IISExpress instance. That will guarantee the issue 'is resolved' (at least until I disconnect again).

**Comment by davidfowl** [comment]
What is WebsocketHandler?

**Comment by NVentimiglia** [comment]
From Microsoft.Web.Websockets ?

`````
// Decompiled with JetBrains decompiler
// Type: Microsoft.Web.WebSockets.WebSocketHandler
// Assembly: Microsoft.WebSockets, Version=0.2.3.0, Culture=neutral, PublicKeyToken=null
// MVID: 5B384535-780C-4B64-BE65-5FF3C5D5F2E8
// Assembly location: E:\Projects\Avarice\Foundation\Foundation-Premium\Foundation Server\packages\Microsoft.WebSockets.0.2.3.1\lib\net45\Microsoft.WebSockets.dll

using System;
using System.ComponentModel;
using System.Threading.Tasks;
using System.Web.WebSockets;

namespace Microsoft.Web.WebSockets
{
  public class WebSocketHandler
  {
    public WebSocketHandler();
    public virtual void OnOpen();
    public virtual void OnMessage(string message);
    public virtual void OnMessage(byte[] message);
    public virtual void OnError();
    public virtual void OnClose();
    public void Send(string message);
    public void Send(byte[] message);
    public void Close();
    [EditorBrowsable(EditorBrowsableState.Never)]
    public Task ProcessWebSocketRequestAsync(AspNetWebSocketContext webSocketContext);
    public int MaxIncomingMessageSize { get; set; }
    public AspNetWebSocketContext WebSocketContext { get; set; }
    public Exception Error { get; set; }
  }
}
``````

**Comment by davidfowl** [comment]
Yea, that package isn't supported and has nothing to do with this repository.
