### ISSUE TITLE
Can Protocol.FrameHeader be a struct?

### ISSUE THREAD

**Issue by benaadams** [aspnet/WebSockets#77]
Popping up in my allocs a lot

**Comment by davidfowl** [comment]
Show some numbers?

**Comment by benaadams** [comment]
Don't entirely understand Perfview but it looks like my 4th biggest allocator, 3 minute trace

![prefview](http://aoa.blob.core.windows.net/aspnet/perfview.png)

**Comment by benaadams** [comment]
Obv have other issues too :)

**Comment by benaadams** [comment]
WebSocketReceiveResult should be a struct https://github.com/dotnet/corefx/issues/4530 :cry:

**Comment by stephentoub** [comment]
Now that this is using the same implementation as from CoreFx, this is no longer an issue, right?

**Comment by benaadams** [comment]
Will reprofile

**Comment by benaadams** [comment]
Think this change is in 0.2.0, have a test tomorrow so keeping version safe on 0.1.0 will try 0.2.0 after.

**Comment by benaadams** [comment]
@stephentoub Yes this is resolved; have a new DisplayClass though - will track down what it is and raise separately if its framework.

![](https://aoa.blob.core.windows.net/aspnet/frameheader.png)
