### ISSUE TITLE
[Question] Does a sample client targeting netstandard exist?

### ISSUE THREAD

**Issue by qooroo** [aspnet/WebSockets#83]
I'm wondering whether a `netstandard` implementation of a websocket client exists. The sample in the current codebase only targets `net451`.

@Tratcher can you point me in the right direction? Cheers

**Comment by Tratcher** [comment]
There wasn't any support for a netstandard client until recently. See https://github.com/dotnet/corefx/blob/d0dc5fc099946adc1035b34a8b1f6042eddb0c75/src/System.Net.WebSockets.Client/src/System/Net/WebSockets/ClientWebSocket.cs

**Comment by qooroo** [comment]
Awesome, thanks for the pointer!

**Comment by qooroo** [comment]
So close, yet so far...

https://github.com/dotnet/corefx/blob/master/src/System.Net.WebSockets.Client/src/System/Net/WebSockets/WebSocketHandle.Unix.cs

@Tratcher do you know whether support on linux will be coming? It's super sad to see a netstandard lib that's not netstandard :(

**Comment by Tratcher** [comment]
No idea, that's a question for corefx.
