### ISSUE TITLE
Bearer token header

### ISSUE THREAD

**Issue by buybackoff** [aspnet/WebSockets#88]
If I need to add a bearer token before handshake so that I accept only the connections that have a valid token, what is the correct way to do so? 

After [this line](https://github.com/aspnet/WebSockets/blob/dev/test/TestClient/Program.cs#L28), should I just add this:
```
WebSocketClient client = new WebSocketClient();
client.ConfigureRequest = (req) =>
{
    req.Headers.Add("Bearer ", _tokenValue);
};
```

That is similar to what I used to do in SignalR. Is this the correct way to make identity middleware work and then use it before accepting a WS request? Thanks!

**Comment by Tratcher** [comment]
Yes, that should work for WebSocketClient. I assume you have something set up on the server side to validate them? JwtBearer?

**Comment by buybackoff** [comment]
Thanks! Yes, I am using ASP.NET Identity + IdentityServer (do not remember from my head where `app.UseOAuthBearerTokens(OAuthOptions);` OWIN middleware comes from). But that already worked with SignalR, I am now moving to plain sockets because of [this issue](https://github.com/aspnet/SignalR-Server/issues/118) and because WebSockets support is near ubiquitous now.

I will keep this issue open for a while until I actually make it work, if you don't mind...

**Comment by buybackoff** [comment]
Here is code for a client:
```
_client = new WebSocketClient {
                ConfigureRequest = (req) => {
                    var header = new AuthenticationHeaderValue("Bearer", _accessToken);
                    req.Headers.Add("Authorization", header.ToString());
                }
            };
```

And for the server inside Configure method:

```
using Microsoft.AspNetCore.Authentication.JwtBearer;
...

            var jwtOptions = new JwtBearerOptions {
                AuthenticationScheme = JwtBearerDefaults.AuthenticationScheme,
                Authority = "https://example.com/id/",
                Audience = "https://example.com",
                AutomaticAuthenticate = true,
                RequireHttpsMetadata = false
            };
            jwtOptions.ConfigurationManager = new ConfigurationManager<OpenIdConnectConfiguration>
                (
                    metadataAddress: jwtOptions.Authority + ".well-known/openid-configuration",
                    configRetriever: new OpenIdConnectConfigurationRetriever(),
                    docRetriever: new HttpDocumentRetriever { RequireHttps = true }
                );
            app.UseJwtBearerAuthentication(jwtOptions);
```
After that `context.User.Identity` is authenticated, claims collection is populated and I could apply any logic before accepting WebSockets.
