### ISSUE TITLE
keep-alive semantics

### ISSUE THREAD

**Issue by cperras** [aspnet/WebSockets#90]
Hi - Can you please clarify how keep-alives are supposed to work?

I would like to ensure that a client is currently connected, eg: by sending a ping every second, and expecting a pong (say, within 3 seconds).

However, the pong response is handled under the covers by the websocket library. There doesn't seem to be a way for my app to know when, or even if, the client ever responds with a pong. 

Note that simply setting a ReadTimeout on the underlying socket stream would solve this problem. I don't see how this is possible with a websocket returned in an aspnet core 1 app via

  var webSocket = await context.WebSockets.AcceptWebSocketAsync();

Am I forced to create my own keep-alive messages? If so, what is the point of websocket ping/pong at all?

thanks,
--craig

**Comment by Tratcher** [comment]
The ping/pongs serve two purposes:
1. They encourage the connection to stay open with occasional traffic (with emphasis on the occasional; 1 second is very high, 30 seconds is more common).
2. Detecting if the connection has been broken. Any outgoing write on a broken connection will trigger a reset from the remote party, causing the pending read on that connection to fail.

So the answer to your real question is that you detect the client disconnect by always keeping a pending read on the WebSocket. Note that the current implementation requires this to process incoming pings anyways.

**Comment by cperras** [comment]
thanks for the quick follow-up. the use-case i am most concerned with is a half-open state, say, by losing a wireless connection or having an ethernet cable unplugged.

enforcing a read-timeout on the underlying TCP stream is one way to check for an unplugged cable.

it's not clear how sending a ping, by itself, is enough to verify the client is still connected (if the client is unreachable), unless you are willing to wait for the TCP protocol itself to timeout (which may be a long time).

**Comment by Tratcher** [comment]
@benaadams do you have trouble detecting disconnects in production?

**Comment by benaadams** [comment]
Not had any issues detecting disconnects and have tested thousands of disconnects a second; clean and through process and VM termination. However, we are generally constantly reading and writing on the sockets. I haven't explored much with mostly idle websockets.

Idle on a good connection it should timeout within 2.5 mins; on a bad connection where transmission has reached 240secs it could take 20mins to timeout? (you should be using `HttpContext.RequestAborted` or a linked token source with it, for ReadAsync and WriteAsync)

**Comment by muratg** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.
