### ISSUE TITLE
Automate Autobahn server test suite

### ISSUE THREAD

**Issue by anurse** [aspnet/WebSockets#95]
Add automation to run the [Autobahn Test Suite](http://autobahn.ws/testsuite/) against the WebSocket middleware

This will involve launching Python so we'll need some scripting to detect Python and fail as appropriate, or install it or something.

* [x] Check in the necessary code to run it on build
* [x] Update CI infrastructure as needed to include necessary support files (Autobahn Runner, etc.)
* [x] Include test apps for HttpListener and ASP.NET 4
* [x] Enable Autobahn runs on each build.
* [x] Provide simple infrastructure to run individual test cases against a server

**Comment by Tratcher** [comment]
With coverage for Kestrel, IIS Express + Kestrel, and WebListener (w/managed).

It would also be convenient to be able to do manual runs against HttpListener and Asp.Net 4 for behavioral comparisons.
