### ISSUE TITLE
Autobahn Failure: UTF-8 handling, WebListener with Managed Web Sockets

### ISSUE THREAD

**Issue by anurse** [aspnet/WebSockets#97]
Tracking a suppressed failure in the Autobahn suite for review and fixing later.

Cases 6.1.2 and 6.1.3 fail on WebListener with the managed web sockets implementation. These appear to be simple tests that send a fragmented UTF-8 message (where each fragment is itself valid UTF-8) and expect the result to be echoed back. However, the connection is being terminated abruptly by the server.

**Comment by muratg** [comment]
Putting in 1.1 for now for further investigation to see if there are possible product bugs in the stack

**Comment by anurse** [comment]
This was fixed by importing the CoreFX code.
