### ISSUE TITLE
Autobahn Failure: Many payloads of zero size, WebListener with Managed Web Sockets

### ISSUE THREAD

**Issue by anurse** [aspnet/WebSockets#98]
Tracking a suppressed failure in the Autobahn suite for review and fixing later.

Cases 9.7.1 and 9.8.1 fail on WebListener with the managed web sockets implementation. These failures occur because when the client sends many zero-size messages, the connection is abruptly terminated by the server.

**Comment by muratg** [comment]
Putting in 1.1 for now for further investigation to see if there are possible product bugs in the stack

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2478
