### ISSUE TITLE
Autobahn Non-Strict-Conformance: UTF-8 fail-fast on Managed WebSockets

### ISSUE THREAD

**Issue by anurse** [aspnet/WebSockets#99]
Tracking a suppressed indication of non-strict-conformance in the Autobahn suite for review and triage later. This is not a failure, just a place where our implementation is not strictly conforming to the spec.

Cases 6.4.3 and 6.4.4 fail on all servers that use the managed WebSockets server implementation. This is due to our server not properly failing-fast when it encounters invalid UTF-8. However, the server is closing the connection, and with the appropriate close reason, so we are still mostly conforming to the spec.

**Comment by muratg** [comment]
Putting in 1.1 for now for further investigation to see if there are possible product bugs in the stack

**Comment by anurse** [comment]
This will be fixed by moving to the CoreFX code. Confirmed that the test now reports strict-conformance in these cases with that code.
